export const SITE_CONFIG = {
  company: {
    name: '(주)오션테크',
    nameEn: 'Ocean Tech Inc.',
    ceo: '이우철',
    bizNo: '127-87-02624',
    corpNo: '284111-0408596',
    slogan: '바다와 함께 공생하는 기업',
    sloganSub: '건강한 바다, 행복한 어민',
  },
  contact: {
    tel: '031-566-7720',
    fax: '031-556-7721',
    email: 'oceantee@naver.com',
    manager: '이채진 전무이사',
    mobile: '010-6348-1210',
  },
  address: {
    main: '남양주시 다산순환로 20 현대프리미어캠퍼스 E동 7층 29-30호',
    office: '남양주시 다산순환로 20 현대프리미어캠퍼스 E동 7층 29-30호',
    headOffice: '경기 남양주시 경춘로773번길 12-33(일패동) 101호',
    lab: '서울 광진구 이자산로 375 크레신타워 B1~408호',
  },
  domain: 'oceantechinc.com',
  certifications: {
    greenTech: {
      nameKo: '녹색기술인증',
      nameEn: 'Green Technology Certification',
      number: 'GT-25-02356',
      period: '2025.07.24 ~ 2029.07.23',
      issuerKo: '환경부',
      issuerEn: 'Ministry of Environment',
      techNameKo: '친환경 어망추 제조방법',
      techNameEn: 'Eco-friendly fishing weight manufacturing method',
    },
    greenProduct: {
      nameKo: '녹색기술제품확인',
      nameEn: 'Green Product Verification',
      number: 'GTP-25-04857',
      period: '2025.07.24 ~ 2029.07.23',
      issuerKo: '한국환경산업기술원',
      issuerEn: 'KEITI',
      techNameKo: '아연합금 기반 유해물질 배출 절감 그물추 제조기술',
      techNameEn: 'Zinc alloy-based eco-friendly fishing weight manufacturing technology',
      basisKo: '탄소중립기본법 제60조',
      basisEn: 'Framework Act on Carbon Neutrality, Article 60',
      confirmationNumber: 'GTP-25-04857',
    },
    venture: {
      nameKo: '벤처기업 확인',
      nameEn: 'Venture Company Certificate',
      number: '2023121403001',
      period: '2023.12.14 ~ 2026.12.13',
      issuerKo: '벤처기업확인기관',
      issuerEn: 'Venture Certification Authority',
    },
    researchDept: {
      nameKo: '기업부설연구소 인정',
      nameEn: 'Corporate R&D Center Recognition',
      number: '2023155066',
      date: '2023.07.23',
      issuerKo: 'KOITA',
      issuerEn: 'KOITA',
    },
    sme: {
      nameKo: '중소기업 확인서',
      nameEn: 'SME Certificate',
      number: '0010-2023-333874',
      issuerKo: '중소벤처기업부',
      issuerEn: 'MSS',
    },
    patentAward: {
      nameKo: '대한민국 우수특허대상',
      nameEn: 'Korea Excellence Patent Award',
      number: '2023 제17회',
      date: '2023.12.27',
      issuerKo: '한국일보',
      issuerEn: 'Hankook Ilbo',
    },
  },
  patents: [
    {
      number: '10-2197917',
      titleKo: '친환경 어장추 제조방법',
      titleEn: 'Eco-friendly Fishing Weight Manufacturing Method',
      date: '2020.12.28',
      image: '/documents/certs/patent-2197917.png',
    },
    {
      number: '10-1887767',
      titleKo: '수중 장애물 탈출 구조 어장추',
      titleEn: 'Fishing Weight with Underwater Obstacle Escape Structure',
      date: '',
      image: '/documents/certs/patent-page5.png',
    },
    {
      number: '10-2508401',
      titleKo: '발광체 구비 수중 장애물 탈출 구조 어장추',
      titleEn: 'Obstacle Escape Fishing Weight with Luminous Body',
      date: '',
      image: '/documents/certs/patent-page6.png',
    },
    {
      number: '10-1895932',
      titleKo: '문어 유인용 낚시기구',
      titleEn: 'Octopus Luring Fishing Gear',
      date: '',
      image: null,
    },
    {
      number: '10-1622799',
      titleKo: '어구 부력체',
      titleEn: 'Fishing Gear Buoyancy Body',
      date: '',
      image: null,
    },
    {
      number: '10-1802799',
      titleKo: '어장추용 내구성 증대 구조',
      titleEn: 'Durability-enhanced Structure for Fishing Weights',
      date: '',
      image: null,
    },
  ],
  patentApplications: [
    { number: '10-2023-0070861', titleKo: '친환경 어망추 제조방법 및 그에 의해 제조된 어망추', titleEn: 'Eco-friendly Fishing Net Weight Manufacturing Method', date: '2023.06' },
    { number: '10-2023-0070872', titleKo: '친환경 소재를 이용한 에어포켓 타입의 어구용 부자', titleEn: 'Air-pocket Type Fishing Buoy with Eco-friendly Material', date: '2023.06' },
    { number: '10-2023-0070875', titleKo: '친환경 소재를 이용한 어구용 부자', titleEn: 'Fishing Buoy with Eco-friendly Material', date: '2023.06' },
    { number: '10-2023-0070877', titleKo: '친환경 소재를 이용한 에어포켓 타입의 부표', titleEn: 'Air-pocket Type Buoy with Eco-friendly Material', date: '2023.06' },
    { number: '10-2023-0070881', titleKo: '친환경 문어 어획용 낚시어구 제조방법', titleEn: 'Eco-friendly Octopus Fishing Gear Manufacturing Method', date: '2023.06' },
    { number: '10-2023-0070882', titleKo: '친환경 채낚기 추 제조방법 및 그에 의해 제조된 채낚기 추', titleEn: 'Eco-friendly Jigging Weight Manufacturing Method', date: '2023.06' },
  ],
  designPatents: [
    { titleKo: '어망추', titleEn: 'Fishing Weight', count: 2 },
    { titleKo: '낚시용 발광체', titleEn: 'Fishing Luminous Body', count: 1 },
    { titleKo: '문어 유인기 미끼', titleEn: 'Octopus Lure Bait', count: 1 },
  ],
  documents: {
    certificates: [
      {
        key: 'greenTech',
        titleKo: '녹색기술인증서',
        titleEn: 'Green Technology Certificate',
        image: '/documents/certs/green-tech-cert.png',
        number: 'GT-25-02356',
        accent: 'mint',
        downloadUrl: '/documents/downloads/green-tech-cert.pdf',
      },
      {
        key: 'greenProduct',
        titleKo: '녹색기술제품확인서',
        titleEn: 'Green Product Certificate',
        image: '/documents/certs/green-product-cert.png',
        number: 'GTP-25-04857',
        accent: 'mint',
        downloadUrl: '/documents/downloads/green-product-cert.pdf',
      },
      {
        key: 'venture',
        titleKo: '벤처기업 확인서',
        titleEn: 'Venture Company Certificate',
        image: '/documents/certs/venture-cert.png',
        number: '2023121403001',
        accent: 'blue',
        downloadUrl: '/documents/downloads/venture-cert.pdf',
      },
      {
        key: 'researchDept',
        titleKo: '기업부설연구소 인정서',
        titleEn: 'Corporate R&D Center Recognition',
        image: '/documents/certs/research-dept.png',
        number: '2023155066',
        accent: 'blue',
        downloadUrl: '/documents/downloads/research-dept-cert.pdf',
      },
      {
        key: 'sme',
        titleKo: '중소기업 확인서',
        titleEn: 'SME Certificate',
        image: '/documents/certs/sme-cert.png',
        number: '0010-2023-333874',
        accent: 'blue',
        downloadUrl: '/documents/downloads/sme-cert.pdf',
      },
      {
        key: 'patentAward',
        titleKo: '대한민국 우수특허대상',
        titleEn: 'Korea Excellence Patent Award',
        image: '/documents/certs/patent-award-2023.png',
        number: '2023 제17회',
        accent: 'gold',
      },
      {
        key: 'svhc',
        titleKo: 'SVHC 보고서',
        titleEn: 'SVHC Report',
        image: '/documents/certs/svhc-report.png',
        number: '235종 불검출',
        accent: 'mint',
        downloadUrl: '/documents/downloads/svhc-report.pdf',
      },
      {
        key: 'testTak',
        titleKo: '시험성적서 TAK',
        titleEn: 'Test Report TAK',
        image: '/documents/certs/test-report-tak.png',
        number: 'TAK-2024-008089',
        accent: 'blue',
        downloadUrl: '/documents/downloads/test-report-tak.pdf',
      },
      {
        key: 'testTbk',
        titleKo: '시험성적서 TBK',
        titleEn: 'Test Report TBK',
        image: '/documents/certs/test-report-tbk.png',
        number: 'TBK-2024-000252',
        accent: 'blue',
        downloadUrl: '/documents/downloads/test-report-tbk.pdf',
      },
    ],
  },
  history: [
    { year: '2009.05', eventKo: '친환경 어망추 연구개발 착수', eventEn: 'Started R&D on eco-friendly fishing weights' },
    { year: '2015.02', eventKo: '해양추 관련 특허 취득', eventEn: 'Acquired marine weight-related patents' },
    { year: '2017.10', eventKo: '미래산업으로 상호 변경', eventEn: 'Renamed business entity' },
    { year: '2018.01', eventKo: '문어 유인용 낚시기구 특허 취득', eventEn: 'Patented octopus luring fishing gear' },
    { year: '2022.05', eventKo: '수협중앙회 친환경 어망추 국내 최초 단가계약 체결', eventEn: 'Signed the first unit-price contract for eco-friendly weights with SUHYUP' },
    { year: '2023.04', eventKo: '(주)오션테크 법인 설립', eventEn: 'Established Ocean Tech Inc.' },
    { year: '2023.07', eventKo: '기업부설연구소 인정', eventEn: 'Recognized as a corporate R&D center' },
    { year: '2023.12', eventKo: '벤처기업 확인', eventEn: 'Confirmed as a venture company' },
    { year: '2023.12', eventKo: '대한민국 우수특허대상 수상', eventEn: 'Won the Korea Excellence Patent Award' },
    { year: '2025.07', eventKo: '녹색기술인증 및 녹색기술제품확인 동시 취득', eventEn: 'Acquired both green technology and green product certifications' },
  ],
  stats: {
    patents: 6,
    designPatents: 4,
    durability: 10,
    svhc: 235,
    costReduction: 80,
    trialMonths: 31,
    fishingBoats: 19,
  },
  performance: [
    {
      year: '2022',
      itemsKo: ['수협중앙회 친환경 어망추 단가계약 체결', '강원 고성군 실증사업 납품 개시'],
      itemsEn: ['Signed a unit-price contract with SUHYUP', 'Started supply for Goseong pilot program'],
    },
    {
      year: '2023',
      itemsKo: ['강원 고성군 실증사업 지속 납품', '벤처기업 확인 및 우수특허대상 수상'],
      itemsEn: ['Continued supply for the Goseong pilot program', 'Received venture confirmation and excellence patent award'],
    },
    {
      year: '2024',
      itemsKo: ['TAK/TBK 시험성적서 확보', 'SVHC 235종 불검출 보고서 확보'],
      itemsEn: ['Secured TAK/TBK test reports', 'Secured SVHC non-detection report for 235 substances'],
    },
  ],
  news: [
    {
      titleKo: "중금속 납추 대신 바다 생태계 지키는 친환경 대체재 주목",
      titleEn: 'Eco-friendly substitute gains attention as an alternative to toxic lead weights',
      sourceKo: '강원도일보',
      sourceEn: 'Gangwon Domin Ilbo',
      date: '2023.08.17',
      summaryKo: '강원도 기사에서 오션테크의 아연 어망추가 해양 생태계를 보호하는 대안으로 소개됐다.',
      summaryEn: "Gangwon media highlighted Ocean Tech's zinc fishing weights as a practical way to protect marine ecosystems.",
      image: '/images/news/kado-article-2023.png',
    },
    {
      titleKo: '오션테크, 제17회 대한민국 우수특허대상 수상',
      titleEn: 'Ocean Tech wins the 17th Korea Excellence Patent Award',
      sourceKo: '한국일보',
      sourceEn: 'Hankook Ilbo',
      date: '2023.12.27',
      summaryKo: '친환경 어망추 제조기술의 독창성과 사업성을 인정받아 기계·해양 부문 대상을 수상했다.',
      summaryEn: 'The company was recognized for the originality and commercial value of its eco-friendly fishing weight technology.',
      image: '/images/news/hankook-article-2023.png',
    },
    {
      titleKo: '강원 고성군 31개월 실증사업 완료, 비용 절감과 내구성 검증',
      titleEn: '31-month field pilot verified cost savings and durability',
      sourceKo: '오션테크',
      sourceEn: 'Ocean Tech',
      date: '2024.03',
      summaryKo: '실제 어업 현장에서 31개월 동안 사용하며 교체 비용 절감과 내구성이 검증됐다.',
      summaryEn: 'A 31-month field pilot confirmed durability and strong replacement cost savings in real fishing conditions.',
      image: '/images/products/install-page11.png',
    },
    {
      titleKo: '녹색기술인증과 녹색기술제품확인 동시 취득',
      titleEn: 'Acquired both green technology and green product certifications',
      sourceKo: '환경부',
      sourceEn: 'Ministry of Environment',
      date: '2025.07',
      summaryKo: '핵심 제조기술과 제품 경쟁력을 동시에 공식 인증받으며 대표 친환경 기술 기업으로 자리매김했다.',
      summaryEn: 'The company secured formal recognition for both its core technology and product competitiveness.',
      image: '/images/green-cert-mark.png',
    },
  ],
  ceoMessage: {
    ko: [
      '바다와 공생하는 건강한 생태계를 만드는 일은 선택이 아니라 책임입니다.',
      '오션테크는 친환경 아연 어망추를 통해 납추를 대체하고, 해양 생태계와 어민의 삶을 동시에 지키는 기술을 만들고 있습니다.',
      '수협중앙회와의 계약, 31개월 현장 실증, 녹색기술 인증은 저희가 걸어온 길이 현장성과 공공성을 모두 갖추고 있음을 보여줍니다.',
      '앞으로도 바다와 어민, 산업이 함께 지속될 수 있도록 더 나은 기술과 더 단단한 실행으로 답하겠습니다.',
      '(주)오션테크 대표이사 이우철',
    ],
    en: [
      'Building a healthier marine ecosystem is not an option. It is our responsibility.',
      'Ocean Tech develops eco-friendly zinc fishing weights that replace lead and protect both marine life and the livelihood of fishers.',
      'Our contract with SUHYUP, 31-month field pilot, and green certifications prove that our technology works in the real world.',
      'We will continue to deliver practical innovation so the ocean, the industry, and fishing communities can thrive together.',
      'Lee Woo-chul, CEO of Ocean Tech Inc.',
    ],
  },
} as const;

export const NAV_ITEMS = [
  { label: '홈', labelEn: 'Home', href: '/' },
  {
    label: '회사소개',
    labelEn: 'About',
    href: '/about',
    children: [
      { label: 'CEO 인사말', labelEn: 'CEO Message', href: '/about#ceo' },
      { label: '비전', labelEn: 'Vision', href: '/about#vision' },
      { label: '연혁', labelEn: 'History', href: '/about#history' },
      { label: '회사개요', labelEn: 'Overview', href: '/about#overview' },
    ],
  },
  { label: '기술력', labelEn: 'Technology', href: '/technology' },
  { label: '인증현황', labelEn: 'Certification', href: '/certification', badge: true },
  { label: '친환경', labelEn: 'Sustainability', href: '/sustainability' },
  { label: '문의하기', labelEn: 'Contact', href: '/contact' },
] as const;

export type NavItem = (typeof NAV_ITEMS)[number];
